# process names are case-insensitive
# you can use 'master' to indicate the master channel, or a list of process names to create a group
# you can use 'mic' to control your mic input level (uses the default recording device)
# you can use 'deej.unmapped' to control all apps that aren't bound to any slider (this ignores master, system, mic and device-targeting sessions)
# windows only - you can use 'deej.current' to control the currently active app (whether full-screen or not)
# windows only - you can use a device's full name, i.e. "Speakers (Realtek High Definition Audio)", to bind it. this works for both output and input devices
# windows only - you can use 'system' to control the "system sounds" volume
# important: slider indexes start at 0, regardless of which analog pins you're using!


slider_mapping:
  0: master
  1: chrome.exe
  2: spotify.exe
  3: rocketleague.exe
  4: discord.exe
  5: opera


CommandOptions:
  0:
    type: Null
    actions: Null # No actions for Page
    targets: Null  # No targets for Page
  1:
    type: Application
    actions:
      0: open
      1: close
    targets:
      0: EscapeFromTarkov
      1: Minecraft
      2: discord
  2:
    type: Windowskey
    actions: {}  # No actions for Windowskey
    targets: {}  # No targets for Windowskey
  3:
    type: Audio
    actions: 
      0: Start
      1: Stop
      2: Pause
    targets: {}  # No targets for Audio




Pages:
  - name: GamingPage
    grid:
      - [ { icon: Discord, command: [1, 1, 3] }, { icon: BattleStageGames, command: [1, 1, 1] }, { icon: Minecraft, command: [1, 1, 2] } ]  # build up of command [Type, Task, Target]
      - [ { icon: WindowsStart, command: [2, 1, 1] }, { icon: Spotify, command: [1, 1, 1] }, { icon: Outplayed, command: [1, 1, 1] } ]
      - [ { icon: Start, command: [3, 1, 1] }, { icon: Pause, command: [3, 3, 1] }, { icon: Volume, command: [0, 0, 0] } ]
      - [ { icon: Microfoon, command: [1, 1, 1] }, { icon: NULL, command: [0, 0, 0] }, { icon: NULL, command: [0, 0, 0] } ]

  - name: VolumeControlPage
    volume_controls:
      1: 75
      0: 50
      5: 60



# set this to true if you want the controls inverted (i.e. top is 0%, bottom is 100%)
invert_sliders: false

# settings for connecting to the arduino board
com_port: COM9
baud_rate: 9600

# adjust the amount of signal noise reduction depending on your hardware quality
# supported values are "low" (excellent hardware), "default" (regular hardware) or "high" (bad, noisy hardware)
noise_reduction: default
